Repository cappuccino/cappuccino, pull requests merged in 2018-08, with the labels that each got.

#2739 FIXED: CPDateFormatter not ready for german dates. Fixes #2736
  Foundation/CPDateFormatter.j
Labels: #accepted, #ready-to-commit

#2740 FIXED: CPScroller superfluous setFrame: calls
  AppKit/CPScrollView.j
  AppKit/CPScroller.j
  AppKit/_CPPopUpList.j
Labels: #new

#2744 FIXED: _CPThemeAttribute valueForState was, under some circumstances, ignoring theme settings
  AppKit/CPTheme.j
Labels: #accepted, #ready-to-commit

#2600 fixed: key equivalent takes precedence over event tracking which is not the case in cocoa
  AppKit/CPApplication.j
  Tests/Manual/PopUpButtonEscTest/.gitignore
  Tests/Manual/PopUpButtonEscTest/AppController.j
  Tests/Manual/PopUpButtonEscTest/Info.plist
  Tests/Manual/PopUpButtonEscTest/Jakefile
  Tests/Manual/PopUpButtonEscTest/Resources/MainMenu.xib
  Tests/Manual/PopUpButtonEscTest/Resources/spinner.gif
  Tests/Manual/PopUpButtonEscTest/index-debug.html
  Tests/Manual/PopUpButtonEscTest/index.html
  Tests/Manual/PopUpButtonEscTest/main.j
Labels: #needs-review, AppKit

#2606 fixed: attached sheets were not put to front after calls to makeKeyAndOrderFront: in code
  AppKit/CPWindow/CPWindow.j
  Tests/Manual/SheetWindowOrderFrontIssue/AppController.j
  Tests/Manual/SheetWindowOrderFrontIssue/Info.plist
  Tests/Manual/SheetWindowOrderFrontIssue/Jakefile
  Tests/Manual/SheetWindowOrderFrontIssue/Resources/MainMenu.cib
  Tests/Manual/SheetWindowOrderFrontIssue/Resources/MainMenu.xib
  Tests/Manual/SheetWindowOrderFrontIssue/index-debug.html
  Tests/Manual/SheetWindowOrderFrontIssue/index.html
  Tests/Manual/SheetWindowOrderFrontIssue/main.j
Labels: #needs-review, AppKit

#2607 fixed: deviation from cocoa when calling setTitle:''
  AppKit/CPPopUpButton.j
  Tests/Manual/CPPopUpButtonTest/AppController.j
Labels: AppKit

#2609 fixed: setMinSize: had no effect in platform windows
  AppKit/CPWindow/CPWindow.j
  AppKit/CPWindow/_CPBorderlessBridgeWindowView.j
  AppKit/Platform/CPPlatformWindow.j
  Tests/Manual/CPPlattformWindowMinSize/AppController.j
  Tests/Manual/CPPlattformWindowMinSize/Info.plist
  Tests/Manual/CPPlattformWindowMinSize/Jakefile
  Tests/Manual/CPPlattformWindowMinSize/Resources/spinner.gif
  Tests/Manual/CPPlattformWindowMinSize/index-debug.html
  Tests/Manual/CPPlattformWindowMinSize/index.html
  Tests/Manual/CPPlattformWindowMinSize/main.j
Labels: #needs-review, AppKit

#2705 FIXED: click to key window in the background did not bring it forward (take 2)
  AppKit/CPWindow/CPWindow.j
  Tests/Manual/KeyWindowInTheBackgroundActivation/AppController.j
  Tests/Manual/KeyWindowInTheBackgroundActivation/Info.plist
  Tests/Manual/KeyWindowInTheBackgroundActivation/Jakefile
  Tests/Manual/KeyWindowInTheBackgroundActivation/Resources/MainMenu.cib
  Tests/Manual/KeyWindowInTheBackgroundActivation/Resources/MainMenu.xib
  Tests/Manual/KeyWindowInTheBackgroundActivation/index-debug.html
  Tests/Manual/KeyWindowInTheBackgroundActivation/index.html
  Tests/Manual/KeyWindowInTheBackgroundActivation/main.j
Labels: #new

#2598 FIXED: return key was not swallowed by textview but triggered the default button.
  AppKit/CPTextView/CPTextView.j
  AppKit/CPWindow/CPWindow.j
  Tests/Manual/CPTextView/AppController.j
Labels: #new

#2759 FIXED: CPTrackingArea manual test was using removed method -removeAllTrackingAreas
  Tests/Manual/TrackingArea/AppController.j
Labels: #ready-to-commit

#2691 FIXED: CPSearchField was positionning its menu with hard coded offset
  AppKit/CPSearchField.j
Labels: #accepted, #needs-improvement

#2686 FIXED: Before this PR, loading of a CPTabView from a CIB file could crash the app
  AppKit/CPTabView.j
Labels: #new

#2755 FIXED: Before this PR, when dragging a selected column, selection color remained in place (visual artefact)
  AppKit/CPTableView.j
Labels: #accepted, #needs-improvement

#2758 FIXED: Before this PR, Nib2Cib wasn't using theme attribute "header-view-height"
  Tools/nib2cib/NSTableHeaderView.j
Labels: #accepted, #needs-improvement

#2753 FIXED: Before this PR, starting a column drag within a scrolled down table would scroll the table content to the bottom
  AppKit/CPTableHeaderView.j
Labels: #accepted, #needs-improvement

#2769 Add --rsync-base option to bootstrap.sh
  bootstrap.sh
Labels: #new
