Repository cappuccino/cappuccino, pull requests merged in 2018-03, with the labels that each got.

#2556 Fixed: legacy scrollers used Aristo1 artwork in Aristo2
  AppKit/Themes/Aristo2/Resources/scroller-down-arrow-disabled.png
  AppKit/Themes/Aristo2/Resources/scroller-down-arrow-highlighted.png
  AppKit/Themes/Aristo2/Resources/scroller-down-arrow.png
  AppKit/Themes/Aristo2/Resources/scroller-left-arrow-disabled.png
  AppKit/Themes/Aristo2/Resources/scroller-left-arrow-highlighted.png
  AppKit/Themes/Aristo2/Resources/scroller-left-arrow.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-horizontal-knob-center.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-horizontal-knob-left.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-horizontal-knob-right.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-horizontal-track-center.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-horizontal-track-left.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-horizontal-track-right.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-vertical-knob-bottom.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-vertical-knob-center.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-vertical-knob-top.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-vertical-track-bottom.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-vertical-track-center.png
  AppKit/Themes/Aristo2/Resources/scroller-legacy-vertical-track-top.png
  AppKit/Themes/Aristo2/Resources/scroller-right-arrow-disabled.png
  AppKit/Themes/Aristo2/Resources/scroller-right-arrow-highlighted.png
  AppKit/Themes/Aristo2/Resources/scroller-right-arrow.png
  AppKit/Themes/Aristo2/Resources/scroller-up-arrow-disabled.png
  AppKit/Themes/Aristo2/Resources/scroller-up-arrow-highlighted.png
  AppKit/Themes/Aristo2/Resources/scroller-up-arrow.png
  AppKit/Themes/Aristo2/Resources/scroller-vertical-track-disabled.png
  AppKit/Themes/Aristo2/Resources/scroller-vertical-track.png
  AppKit/Themes/Aristo2/ThemeDescriptors.j
Labels: #needs-review, Theme

#2579 Fixed: The property list test cases can now run on the Node engine.
  Objective-J/CFPropertyList.js
Labels: #ready-to-commit, tools

#2576 New CPTextView delegate methods added
  AppKit/CPText.j
  AppKit/CPTextView/CPTextView.j
  Tests/AppKit/CPTextViewTest.j
  Tests/Manual/CPTextViewDelegateAndNotifications/AppController.j
  Tests/Manual/CPTextViewDelegateAndNotifications/Info.plist
  Tests/Manual/CPTextViewDelegateAndNotifications/Jakefile
  Tests/Manual/CPTextViewDelegateAndNotifications/NotificationStatistics.j
  Tests/Manual/CPTextViewDelegateAndNotifications/Resources/MainMenu.cib
  Tests/Manual/CPTextViewDelegateAndNotifications/Resources/MainMenu.xib
  Tests/Manual/CPTextViewDelegateAndNotifications/index-debug.html
  Tests/Manual/CPTextViewDelegateAndNotifications/index.html
  Tests/Manual/CPTextViewDelegateAndNotifications/main.j
Labels: #accepted, #ready-to-commit, TextView

#2572 Fixed: Nib2Cib will replace a CPTextFieldCell with a CPTextField
  Tools/nib2cib/NSTextField.j
Labels: #accepted, #ready-to-commit

#2563 Fixed: Editing text in tableviews throws DOM exceptions under certain conditions in Chrome
  AppKit/CPTextField.j
  AppKit/CPTokenField.j
Labels: #needs-review, Chrome
