Repository cappuccino/cappuccino, pull requests merged in 2019-06, with the labels that each got.

#2849 Fixed: backspace triggered page back in FireFox
  AppKit/CPCompatibility.j
  AppKit/Platform/DOM/CPPlatformPasteboard.j
Labels: #new

#2844 FIXED: Before this PR, buttons were sometimes missing their alternate image
  Tools/nib2cib/NSButton.j
Labels: #new

#2793 Fixed: Temporary fix so finding the compiler can work both in the Narwhal and Node world
  Objective-J/Executable.js
  Objective-J/FileExecutable.js
Labels: #ready-to-commit, tools

#2820 fixed: typo in function call to _CPDecimalSetZero
  Foundation/CPDecimal.j
  Tests/Foundation/CPDecimalNumberTest.j
Labels: #needs-review

#2827 FIXED: Before this PR, under certain circumstances, CPControl didn't declare its tracking areas soon enough.
  AppKit/CPControl.j
Labels: #new

#2845 FIXED: Before this PR, cell based table views that use specific font, reverted to standard font when selected/editing
  Tools/nib2cib/NSTableColumn.j
Labels: #new

#2850 Fixed: If sourcemap is available include it when building with a nondebug version of the tools.
  Objective-J/Executable.js
Labels: #new

#2776 fixed: smart copy/paste cycle was leaving an additional whitespace on the LHS
  AppKit/CPTextView/CPTextView.j
Labels: #ready-to-commit, TextView

#2846 FIXED: CPSearchField menu was broken
  AppKit/CPSearchField.j
Labels: #new
