Repository cappuccino/cappuccino, pull requests merged in 2019-04, with the labels that each got.

#2821 fixed: typo in initWithGraphicsPort: declaration
  AppKit/CPGraphicsContext.j
Labels: #ready-to-commit

#2822 fixed: accidental creation of a global variable in CPCursor.j
  AppKit/CPCursor.j
Labels: #ready-to-commit

#2823 fixed: CPBrowserDelegate_browser_imageValueForItem_ was defined twice
  AppKit/CPBrowser.j
Labels: #ready-to-commit

#2794 Fixed: the class method +initialize was always sent even if the root class did not implement it.
  Objective-J/Runtime.js
  Tests/Objective-J/MethodDispatchTest.j
Labels: #ready-to-commit, Foundation

#2786 FIXED: CPStepper was not receiving the enabled status from IB
  AppKit/CPStepper.j
  Tools/nib2cib/NSStepper.j
Labels: #ready-to-commit, tools

#2826 fixed: wrong return type of forward::
  Foundation/CPProxy.j
Labels: #new

#2825 fixed: wrong return type of textField method in
  AppKit/CPTableHeaderView.j
Labels: #new

#2824 fixed: return type of openUntitledDocumentOfType:display:
  AppKit/CPDocumentController.j
Labels: #new

#2819 fixed: removed outdated duplicate method definitions in CPFontManager.j
  AppKit/CPFontManager.j
Labels: #ready-to-commit
