Repository cappuccino/cappuccino, pull requests merged in 2020-03, with the labels that each got.

#2889 FIXED: Before this PR, CPButton never declares that its label should be single line
  AppKit/CPButton.j
Labels: #new

#2888 FIX: Before this PR, the method attributeBySettingValue ignored existing values
  AppKit/CPTheme.j
Labels: #new

#2887 FIXED: Before this PR, a click in a not first key responder CPTextField would misplace the caret if text alignment was not CPLeftTextAlignment
  AppKit/CPTextField.j
Labels: #new

#2886 fixed: _glyphsFrames and _glyphsOffsets could be used uninitialized
  AppKit/CPTextView/CPLayoutManager.j
Labels: #new

#2831 FIXED: Before this PR, only CPControl could use nib2cib-adjustment-frame.
  AppKit/CPControl.j
  AppKit/CPView.j
  Tools/nib2cib/NSControl.j
  Tools/nib2cib/NSView.j
Labels: #needs-improvement, Theme

#2828 FIXED: Before this PR, CPControl setTextColor was missing theme state specification
  AppKit/CPControl.j
Labels: Theme

#2169 New: CPTextField now supports the CPEditorRegistrationProtocol
  AppKit/CPArrayController.j
  AppKit/CPDatePicker/CPDatePicker.j
  AppKit/CPObjectController.j
  AppKit/CPTextField.j
Labels: #ready-to-commit, AppKit

#2688 FIXED: CPTextField forced height to 29 instead of using theme value min-size
  AppKit/CPTextField.j
Labels: #needs-improvement, Theme
