Repository cappuccino/cappuccino, pull requests merged in 2020-10, with the labels that each got.

#2908 FIXED: Before this PR, the classname was not specified in the correct DOM element
  AppKit/CPImage.j
Labels: #new, FIFO

#2912 FIXED: CPColor restorePreviousCSSState method must be a class method
  AppKit/CPColor.j
  AppKit/CPView.j
Labels: #new, FIFO

#2909 NEW: Material icon image
  AppKit/CPImage.j
  AppKit/CPImageView.j
  AppKit/Cib/_CPCibCustomResource.j
  AppKit/Resources/fonts/MaterialIcons-Regular.eot
  AppKit/Resources/fonts/MaterialIcons-Regular.ijmap
  AppKit/Resources/fonts/MaterialIcons-Regular.svg
  AppKit/Resources/fonts/MaterialIcons-Regular.ttf
  AppKit/Resources/fonts/MaterialIcons-Regular.woff
  AppKit/Resources/fonts/MaterialIcons-Regular.woff2
  AppKit/Resources/fonts/material-icons.css
  AppKit/_CPImageAndTextView.j
  Tools/nib2cib/NSCustomResource.j
Labels: #new, FIFO

#2916 NEW: This PR adds a class method to BKThemeDescriptor that enables a view to inherit theme values of another view
  AppKit/Themes/BlendKit/BKThemeDescriptor.j
  AppKit/_CPObject+Theme.j
Labels: #new, FIFO

#2919 NEW: This PR makes system font themable
  AppKit/CPControl.j
  AppKit/CPFont.j
  AppKit/CPTheme.j
Labels: #new, FIFO

#2920 Aristo3: CPButton
  AppKit/CPButton.j
  Tests/AppKit/CPButtonTest.j
  Tests/AppKit/Resources/SimpleBindingsAdoption_03.cib
  Tests/AppKit/WithAndWithoutBindingsIntegration/02_WithBindings/Resources/02_WithBindings.cib
  Tools/nib2cib/NSButton.j
Labels: #new, FIFO

#2921 Aristo3 : CPCheckBox (needs #2920)
  AppKit/CPCheckBox.j
Labels: #new

#2924 Aristo3: CPBox
  AppKit/CPBox.j
  Tools/nib2cib/NSBox.j
Labels: #new, FIFO

#2913 FIXED: Before this PR, when using a custom view with subviews, subviews were presented in the reversed order
  Tests/Manual/Nib2CibSubviewsOrderTest/AppController.j
  Tests/Manual/Nib2CibSubviewsOrderTest/Info.plist
  Tests/Manual/Nib2CibSubviewsOrderTest/Jakefile
  Tests/Manual/Nib2CibSubviewsOrderTest/Resources/MainMenu.cib
  Tests/Manual/Nib2CibSubviewsOrderTest/Resources/MainMenu.xib
  Tests/Manual/Nib2CibSubviewsOrderTest/index-debug.html
  Tests/Manual/Nib2CibSubviewsOrderTest/index.html
  Tests/Manual/Nib2CibSubviewsOrderTest/main.j
  Tools/nib2cib/NSCustomView.j
Labels: #new

#2904 Fix: CPKeyedArchiver method call does not match selector tested
  Foundation/CPKeyedArchiver.j
Labels: #new

#2922 Aristo3: CPRadio (needs #2920)
  AppKit/CPRadio.j
Labels: #new

#2925 Aristo3: CPTextField
  AppKit/CPControl.j
  AppKit/CPTextField.j
  Tools/nib2cib/NSTextField.j
Labels: #new

#2892 Fixed: Loading cached theme attributes will miss previous cached value.
  AppKit/_CPObject+Theme.j
Labels: AppKit

#2941 FIXED: This PR supports modern Cocoa behavior regarding radio buttons groups.
  AppKit/CPRadio.j
  Tests/AppKit/CPButtonTest.j
Labels: #needs-ui-test, #new

#2926 Aristo3: CPSlider
  AppKit/CPLevelIndicator.j
  AppKit/CPSlider.j
  Tools/nib2cib/NSSlider.j
Labels: #new

#2943 FIXED: Before this PR, CPButton's won't display their title
  AppKit/CPControl.j
Labels: #new

#2928 NEW: This PR adds the ability to control CPPopoverWindow background color.
  AppKit/CPWindow/_CPPopoverWindowView.j
  AppKit/_CPPopoverWindow.j
Labels: #new

#2927 Aristo3: CPWindow
  AppKit/CPWindow/CPWindow.j
  AppKit/CPWindow/_CPWindowView.j
Labels: #new

#2930 FIXED: This PR specifies correct / complete theme states for themed values
  AppKit/CPStepper.j
Labels: #new

#2929 Aristo3: Menus (needs #2919)
  AppKit/CPMenu/CPMenu.j
  AppKit/CPMenu/_CPMenuBarWindow.j
  AppKit/CPMenu/_CPMenuManager.j
  AppKit/CPMenu/_CPMenuWindow.j
  AppKit/CPMenuItem/_CPMenuItemSeparatorView.j
  AppKit/CPMenuItem/_CPMenuItemStandardView.j
Labels: #new

#2945 Aristo3: This PR adds the missing -isCSSBased method to CPView
  AppKit/CPView.j
Labels: #new

#2923 NEW: This PR adds a new theme parameter "menu-offset" to CPPopUpButton instead of hard coded value
  AppKit/CPPopUpButton.j
Labels: #new

#2931 NEW: This PR provides more information on an error message in CPScroller
  AppKit/CPScroller.j
Labels: #new

#2934 Aristo3: CPSearchField
  AppKit/CPSearchField.j
  Tools/nib2cib/NSSearchField.j
Labels: #new

#2947 FIXED: default bezel style is now set to CPRoundRectBezelStyle
  AppKit/CPButton.j
Labels: #new

#2948 FIXED: Before this PR, CPStepper wouldn't display correctly
  AppKit/CPStepper.j
Labels: #new

#2949 FIXED: Before this PR, placing a CPTableView in a CPBox would break nib2cib
  Tools/nib2cib/NSTableView.j
Labels: #new
