Repository cappuccino/cappuccino, pull requests merged in 2020-02, with the labels that each got.

#2885 Fixed: CPPredicate does never evaluate to true for 'something != nil'
  Foundation/CPPredicate/CPComparisonPredicate.j
  Tests/Foundation/CPPredicateTest.j
Labels: #new

#2884 fixed: documentation for attributedStringWithAttachment: was missing
  AppKit/CPTextView/CPLayoutManager.j
  AppKit/CPTextView/CPTextStorage.j
Labels: documentation

#2871 New: The compiler will now create warnings for variables that are never read
  AppKit/Jakefile
  AppKit/Themes/BlendKit/Jakefile
  Foundation/Jakefile
  Objective-J/CommonJS/lib/objective-j/compiler.js
  Objective-J/Jakefile
  Objective-J/ObjJAcornCompiler.js
  Objective-J/OldBrowserCompatibility.js
  Tests/Objective-J/Preprocessor/BehaviorTests/IvarTest.j
  Tests/Tools/ToolsTest.j
  Tools/nib2cib/Jakefile
Labels: tools

#2876 NEW: CPSplitView modern Cocoa behavior implementation
  AppKit/CPSplitView.j
  Tests/AppKit/CPSplitViewTest.j
  Tools/nib2cib/NSSplitView.j
Labels: #new
