Repository cappuccino/cappuccino, pull requests merged in 2021-07, with the labels that each got.

#2973 Fix Java version check to cleanly identify both Oracle and OpenJDK va…
  bootstrap.sh
Labels: #new

#2988 fixed: CPButton's images were lost when becoming disabled
  AppKit/CPButton.j
Labels: #ready-to-commit, Theme

#2987 fixed: CPSearchField's bezel did not resize
  AppKit/CPSearchField.j
Labels: #ready-to-commit, Theme

#2990 FIXED: Before this PR, CPButton would always have the same label text size whatever the control size
  AppKit/Themes/Aristo2/ThemeDescriptors.j
Labels: Theme
