Repository cappuccino/cappuccino, pull requests merged in 2021-11, with the labels that each got.

#3008 Include commented-out code to hide mainMenu in NibApplication template
  Tools/capp/Resources/Templates/NibApplication/AppController.j
Labels: #ready-to-commit

#3001 Fixed: Bezel state ivar _bezelState must remove current state when changing to a new.
  AppKit/CPButton.j
Labels: #ready-to-commit, Theme

#2999 Implement missing indexPath method for CPTreeNode
  AppKit/CPTreeNode.j
Labels: Foundation, #ready-to-commit

#2995 FIXED: Before this PR, nib2cib would fail if, for some "not ready" condition, no superview is defined for a view
  AppKit/CPView.j
Labels: tools, #ready-to-commit
